### ISSUE TITLE
Support user credentials option in addition to service account

### ISSUE THREAD

**Issue by Di-Ku** [GoogleCloudPlatform/datalab#450]
I can't seem to find the issue (if I had logged one before). It is tracked as a feature in spreadsheet but making sure that it is tracked here as well.

Scenario:
Someone else owns data but is willing to grant read-only access to a user based on trust in the user and a "need-to-know" verification. Organizationally, most companies do not have an easy workflow for granting access to roles - which can in turn have service account or service accounts for exploratory/development (i.e. non-prod) work. 
Once a user gets access to say BQ or GCS data, they expect to be able to use Datalab to access that data. But currently, the user has to request access for a project-wide service account.

Solution:
Allow user the option of using his/her own creds instead of service account creds. 
One consequence will be that the notebook may note be runnable for another project member (editor). However, that limitation may not matter in many cases - either because there is no other user who cares or because the user with access creates a derived table / file in the project that is used for further analysis.

**Comment by tuanvu216** [comment]
Yes, following on this topic. Can you support oauth using existing client id instead of using one shared service account?

Or even better something similiar to Jupyter Hub? a multi user jupyter notebook server.

**Comment by gramster** [comment]
I think we can close this; user accounts can be used when running locally.
