### ISSUE TITLE
Find and replace "ipython" in sample notebooks

### ISSUE THREAD

**Issue by Di-Ku** [GoogleCloudPlatform/datalab#482]
Example:
In "BigQuery - Extracting Data"

gcs_bucket = gcp.Context.default().project_id + '-ipython'

Bucket names etc should also avoid "ipython". Primarily because the name should not be used per license and secondarily because we don't want to create confusion between IPython & Datalab.

**Comment by gramster** [comment]
Given we have very few references and should rarely need them, and that lawyers have OKed them anyway so they are not a ship stopper, I'm closing this.
