### ISSUE TITLE
Deployer should check for allowed names for reasonable error msg (no uppercase allowed)

### ISSUE THREAD

**Issue by Di-Ku** [GoogleCloudPlatform/datalab#498]
URL parms used:
https://stage-dot-cloud-datalab-deploy.appspot.com/?container=gcr.io/cloud_datalab/datalab:nikhilko_jupyter&name=NewUx

Result:
Generic error message about enabling billing etc. All inapplicable

Retried with current deployer
Log:
Sep  9 02:18:25 datalab-deploy startupscript: You are about to deploy the following modules:
Sep  9 02:18:25 datalab-deploy startupscript:  - datalab-ux/datalab/NewUX  From: [/datalab/app.yaml]
Sep  9 02:18:29 datalab-deploy startupscript: Updating module [datalab] from file [/datalab/app.yaml]
Sep  9 02:18:29 datalab-deploy startupscript: ERROR: Invalid repository name (datalab-ux.datalab.NewUX), only [a-z0-9-_.] are allowed

**Comment by qimingj** [comment]
Deployer handles the uppercase name now.
