### ISSUE TITLE
Inform user about available update (new container version) and provide a link to deployer

### ISSUE THREAD

**Issue by Di-Ku** [GoogleCloudPlatform/datalab#529]
Currently, there is no mechanism to inform a user that the currently running container is stale or should be updated. This can be handy for:
1. Critical patches
2. Significant new features that may be interesting for a user

The proposed feature would compare currently running version with the most up-to-date one and prompt a user to take action. 

A corresponding change will be required in the deployer as well. I will log that elsewhere separately.

**Comment by gramster** [comment]
Fixed in a9b99b865b813b7444a41a05db5537f4912d7d75
