### ISSUE TITLE
Support for creating schemas with nested records

### ISSUE THREAD

**Issue by nikhilk** [GoogleCloudPlatform/datalab#595]
Try this:

    sample_row = {
      'name': 'string value',
      'value': 0,
      'flag': True,
      'location': {
        'lat': 0.0, 'lon': 0.0
      }
    }
    sample_schema = bq.Schema.from_data([sample_row])

The result is a schema that contains 4 fields. Location is of type string.

Expected a schema that contained a RECORD type.

**Comment by gramster** [comment]
Fixed in 3d6c9e59500aba46680f2d45441d8e1d58fce262
