### ISSUE TITLE
UDF syntax woes

### ISSUE THREAD

**Issue by nikhilk** [GoogleCloudPlatform/datalab#606]
Can't seem to make the intuitive work.

Cell 1:
````
%%bigquery udf --module word_filter
...
````

# First Attempt
Cell 2:
````
%%sql

DEFINE QUERY words
  SELECT word, word_count AS count, corpus
  FROM [publicdata:samples.shakespeare]
  WHERE length(word) >= 5

SELECT word, sum(count) as count
FROM $word_filter($words)
GROUP BY word 
ORDER BY count DESC
LIMIT 100
````

**Result -- error: Encountered " "FROM" "FROM "" at line 2, column 1.**

# Second Attempt
Cell 2 (added module name)
````
%%sql --module aaa

DEFINE QUERY words
  SELECT word, word_count AS count, corpus
  FROM [publicdata:samples.shakespeare]
  WHERE length(word) >= 5

SELECT word, sum(count) as count
FROM $word_filter($words)
GROUP BY word 
ORDER BY count DESC
LIMIT 100
````
Cell 3:
````
bq.Query(aaa, word_filter=word_filter).sql
````

Output:
````
u'SELECT word, sum(count) as count\nFROM &lt;gcp.bigquery._udf.UDF object at 0x7fcd4a3c6c50&gt;((SELECT word, word_count AS count, corpus\n  FROM [publicdata:samples.shakespeare]\n  WHERE length(word) >= 5))\nGROUP BY word \nORDER BY count DESC\nLIMIT 100'
````

**Note -- odd &lt;gcp.bigquery._udf.UDF object at 0x7fcd4a3c6c50&gt; in SQL

What am I missing? Whats the way to use these in the way other samples show using SQL.

Desired usage:

- None of the $ syntax. It should mimic what users see in the BigQuery docs.

- Perhaps all UDFs should be automatically included (or some heuristic where UDF names appearing in the SQL are automatically included rather than all).

- UDFs shouldn't be handled as parameter values.

I think we need to address this stuff before we put out the UDF feature in beta, otherwise we risk breaking changes.

In the context of breaking changes, we'll want to also change the unit testing of JavaScript, so it isn't run on the client, but rather in BigQuery.

Maybe we need to take a bigger look at UDFs before putting them out.

**Comment by gramster** [comment]
I'd like to understand a bit the motivation behind the comment "we'll want to also change the unit testing of JavaScript, so it isn't run on the client, but rather in BigQuery.". 

The BigQuery team's own UDF test tool runs UDFs in the client (http://storage.googleapis.com/bigquery-udf-test-tool/testtool.html). It doesn't cost the user any money and is simple. Why would we do differently?

To run these as tests in BigQuery (which you could do already by invoking them in SQL) with (say) JSON or Python list of dictionaries as test data would be slower and more complex, and presumably involve the creation of temporary tables. That seems to be adding cost but not benefit.

**Comment by gramster** [comment]
Most of this was addressed in the UDF changes in last release.
