### ISSUE TITLE
Support Python tuples for variable expansion

### ISSUE THREAD

**Issue by gramster** [GoogleCloudPlatform/datalab#615]
Useful for IN clauses.

**Comment by gramster** [comment]
Suggest taking this for beta1 as it is one of those areas where you get nice synergy between Python and SQL (and its been requested by an alpha customer).

**Comment by geekraver** [comment]
Should support lists too.

**Comment by gramster** [comment]
Fixed in 01fc5da2eb698986ee3c38d99f1ac5ec8db35485
