### ISSUE TITLE
Feature: Make charts viewable in converted html

### ISSUE THREAD

**Issue by Di-Ku** [GoogleCloudPlatform/datalab#652]
(Customer request from an email exchange - discussed before but logging for easier tracking)
Currently charts don't show up in the html page created using Notebook -> Convert to HTML. Request is to change that so charts do show up.

A corollary is to be able to share it with a broader group that may or may not have privileges to run the notebook or access the data sources directly. Based on discussion with Graham, this should not be a problem because the data is already present in charts.

**Comment by gramster** [comment]
It's possible that all that is needed is to change the require.js scripts in the head; e.g.:

    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="extensions/charting" src="./extensions/charting.js"></script>

to have src attributes pointing to the same scripts in a CDN, and that may be possible through nbconvert customization, but that stuff is pretty poorly documented.

**Comment by gramster** [comment]
I've gotten this to work as follows:

Adding this to the <head> element to the HTML file:

    <script>
      require.config({
          paths: {
                  'extensions/charting': 'https://storage.googleapis.com/datastudio-test/charting',
                  'element': 'https://storage.googleapis.com/datastudio-test/element',
                  'style': 'https://storage.googleapis.com/datastudio-test/style',
                  'visualization': 'https://storage.googleapis.com/datastudio-test/visualization'
          }
      });
    </script>
    <style type="text/css" src="https://storage.googleapis.com/datastudio-test/charting.css"></style>
    <style type="text/css" src="https://storage.googleapis.com/datastudio-test/datalab.css"></style>

I'm not sure if the two style elements are really needed. Obviously I had to upload the *.js files to GCS to serve them.

I'm injecting this by hand right now; would need to see if I can get nbconvert to do it automatically.

I also had to change one line in visualization.js, where we used a src attribute with a value that started with // instead of https//; I added the https.

**Comment by gramster** [comment]
Made a bit more progress - put the above changes in a Jinja template that I then customize IPython to use. If I run ipython nbconvert on the command line inside my docker container the conversion works. Unfortunately if I do so from the browser it isn't picking up the customization. I've posted on the Jupyter DL about this so hopefully will get some help.

**Comment by gramster** [comment]
WIP is in https://github.com/GoogleCloudPlatform/datalab/tree/pygcp/ext_tables

Still not working when doing the save from the browser.

**Comment by nikhilk** [comment]
I think we'd simply write our own nbconvert equivalent and call that instead of customizing the standard one. Ultimately, I think we'll want a lot more control over exactly what gets published...

**Comment by gramster** [comment]
Well, I do have it working now in that branch.

**Comment by gramster** [comment]
Fixed in e2187a7

**Comment by qdw-luke** [comment]
Been using it and it looks good.

Luke

Sent from my iPhone

On Dec 7, 2015, at 7:21 PM, Graham Wheeler <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #652<https://github.com/GoogleCloudPlatform/datalab/issues/652>.

-
