### ISSUE TITLE
Error message when trying to revert a file in git from within datalabs

### ISSUE THREAD

**Issue by parthea** [GoogleCloudPlatform/datalab#667]
Hello,

I'm unable to resolve a conflict in datalabs. I'm not sure if this is the correct place to report the error, so please let me know if I should post the question somewhere else.

I receive an error message when I try to revert a conflicted file in datalabs. I've included a screenshot of the error message that appears after I click "Revert all" to revert all my local changes and accept the server's copy.

![error](https://cloud.githubusercontent.com/assets/5184014/10944843/13aaa68e-82e9-11e5-9580-ac4272374a82.png)
![revertall popup](https://cloud.githubusercontent.com/assets/5184014/10944841/13a956ee-82e9-11e5-8556-d183f4cf677b.png)
![conflict1](https://cloud.githubusercontent.com/assets/5184014/10944842/13aa7ace-82e9-11e5-9e41-7d0a939e47cb.png)

**Comment by parthea** [comment]
One potential workaround is to use the command line git from within datalabs. For example,

```
%%bash
git status
```

**Comment by qimingj** [comment]
Thanks for reporting this. Is it consistent?

**Comment by parthea** [comment]
Yes. The error message still appears when I click "Revert all". Another colleague of mine has the same issue.  We are using the same git repository. I am currently using the workaround in order to pull/push to the git repository.

**Comment by qimingj** [comment]
Can you go to Developer Console, click Development (or if you are on old Console, click Browse under Source), and send me the URL? It should contain a project Id, and also a repository string. For example:

https://pantheon.corp.google.com/code/develop/browse/TeayaPZ6CBw/master?project=datalab-deploy-test1

Thanks!

**Comment by parthea** [comment]
Thanks for the quick reply @qimingj 

I sent an email direct to @gramster with the url that contains the project id and repository string. I didn't want to post my personal url here.

**Comment by parthea** [comment]
Update: Dec 21, 2015

This issue is still present.

![screenshot from 2015-12-21 14 07 49](https://cloud.githubusercontent.com/assets/5184014/11938932/3e748128-a7ec-11e5-8c12-20dd375be7e2.png)

**Comment by qimingj** [comment]
Let me check with source repository team.

**Comment by KingBobbb** [comment]
Hello, 

I am having the same problem - see attached for screenshot. I simply cannot resolve the conflict for one particular notebook (others in my company are not having the issue with the same file but they are for other notebooks). Only work-around that I've found for now is using the command line method of committing as mentioned previously. 

![2](https://cloud.githubusercontent.com/assets/16402934/11962999/ea443c30-a8b1-11e5-8f48-f1b2dea30fc0.jpg)

**Comment by parthea** [comment]
@qimingj

> Let me check with source repository team.

Can I have their contact email address to follow up?

**Comment by qimingj** [comment]
I chatted with the Development Console team. They got all the information you shared and are still investigating it. It seems the source UI does not deal with conflicts in ipynb files well. In the short term, if you are blocked by this particular occurrence of the issue, you can send us the project id, branch name, user name, and we can reset your workspace (which means your uncommitted changes will be lost). That may fix your workspace issue for the short term.

Of course a long term fix is desired. I'll keep you posted.

**Comment by parthea** [comment]
Closing this issue as I've switch to using the local server setup as opposed to the cloud .

**Comment by ngthuydiem** [comment]
@qimingj: Hi, I'm currently blocked by the exact same problem with datalab . May I check how I can reset my workspace/work around this issue? Thanks!

**Comment by qimingj** [comment]
Hi Kristin,


Can you share with me your project id and also your user id (email) used to
sign in to access Datalab?



Thanks,
Bradley

**Comment by ngthuydiem** [comment]
Hi Bradley, thank you for the quick reply! May I know your email address so that I can send my project details to you?

**Comment by qimingj** [comment]
qimingj@google.com. Thanks!
