### ISSUE TITLE
new folder disappears

### ISSUE THREAD

**Issue by superChing** [GoogleCloudPlatform/datalab#704]
I create a new folder and rename, and after seconds I reload the webpage , the folder disappears.
This happen almost constantly.
Sorry I don't know how to reproduce it here.

**Comment by nikhilk** [comment]
I have not been able to see this happening on my end. Which version are you using? This is shown in the about dialog (click the 'i' icon on top-right).

**Comment by superChing** [comment]
Version: 0.5.20151125
This happened many times today morning, but now works fine.
It is very strange indeed.
