### ISSUE TITLE
Socket closing during request?

### ISSUE THREAD

**Issue by geekraver** [GoogleCloudPlatform/datalab#707]
See http://stackoverflow.com/questions/34093994/google-cloud-datalab-reload-set-from-bigquery-leads-to-respondnotready

Some clues: http://stackoverflow.com/questions/3231543/python-httplib-responsenotready

**Comment by gramster** [comment]
Dug into this some. httplib2 has the ability to reuse a connection but AFAICT it should not do so if the Http object is not being reused (which it isn't). However, it may be prudent to add a "connection: close" header to get the server to close the connection itself after sending a response.

The other possibility might be if it takes a long time to get a response. So we should also add a handler for the ResponseNotReady exception so we can bubble it up as a regular Exception like we do with other errors that are not embedded in a response.

**Comment by gramster** [comment]
Closing this in the hope that it is fixed by 7d3c38688435e5cd337d859670d48fecf27df41a (can't verify as we don't have a reliable repro). We can reopen if we see it in future.
