### ISSUE TITLE
Better handling of insufficient browser width

### ISSUE THREAD

**Issue by gramster** [GoogleCloudPlatform/datalab#713]
If the browser window is narrow a lot of our menubar items disappear. We should address this somehow (quick n dirty might be to detect that and throw up a message like we do with the update message).

**Comment by gramster** [comment]
Fixed in 6edaf9fca5bd7dfb8ce5f388b721423f1de6cf29

**Comment by gramster** [comment]
The 'fix' wasn't so reopening.

**Comment by ojarjur** [comment]
There are two ways to address this issue:

1. Make the layout of the page gracefully scale down to match small window sizes.
2. Set a minimum size for the layout of the page and make the user's window scroll over that page if it is too small to fit the minimum size.

The first option is preferable, but it requires much more sophisticated UI logic than we currently have, so I've instead implemented the second option.

With that, this should now be fixed.
