### ISSUE TITLE
Add a predefined metavar for the current project

### ISSUE THREAD

**Issue by gramster** [GoogleCloudPlatform/datalab#720]
We can get the project in Python code but for those who just want to use magics a variable could be useful.

**Comment by qimingj** [comment]
Would an environment variable sufficient? GAE VM always comes with a predefined variable:

%%bash
printenv GAE_LONG_APP_ID

**Comment by gramster** [comment]
We don't expands those in magics. So really all this is saying is that we set a Python global variable to be the default project ID when we start a notebook.

**Comment by gramster** [comment]
datalab_project_id was added recently.
