### ISSUE TITLE
Chart gauge with ticks is crashing the Datalab

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/datalab#730]
Python code:
```
from pandas import DataFrame

d_sum = {"Label": ["1. LoadRawCSV", "2. RawCSV2DF",
                   "3. DF2CleanCSV", "4. CleanCSV2BQ"],
          "Speed": [10551752, 6670317, 2450890, 376079]}

df_sum = DataFrame(d_sum)
df_sum
```

Explosive code:
```
%%chart gauge -f Label,Speed -d df_sum
title: Speed of each operation (data points per seconds)
max: 10000000
redFrom: 0
redTo: 1000000
yellowFrom: 1000000
yellowTo: 5000000
greenFrom: 5000000
greenTo: 10000000
minorTicks: 1000000
majorTicks: 5000000
```

**Comment by gramster** [comment]
Interesting. I think this is actually a bug in the Google Charts library, not datalab. It is specifically caused by the minorTicks option; if you leave that out things don't crash. We just pass those options through; it looks like that option is causing some kind of infinite loop in the charts library. I'll open a bug against them.

**Comment by VelizarVESSELINOV** [comment]
I agree the problem is coming from Google Chart, but will be great if Google DataLab can survive if Google Chart is crashing.

**Comment by gramster** [comment]
You are asking a lot - Chrome window does not survive this.

**Comment by gramster** [comment]
See for yourself. https://jsfiddle.net/gramster/pdc5zq89/

Hangs Chrome and Safari browser windows; no Datalab involved.

**Comment by VelizarVESSELINOV** [comment]
I can understand that the code is crashing the individual page, but several times (not all the time) datalab session was dead, having several windows open on several datalab pages and all the tabs crashed in my Chrome browser.

Can you please share the ticket so I can follow the progress of the resolution by the Google Chart team?

Thanks

**Comment by gramster** [comment]
The other tabs hanging is unfortunately also related to Chrome, which
limits us to six active web sockets between a (client, server) pair. These
can get multiplexed to some extend but if the tab goes down it ties up
those sockets.

The bug I filed against Charts was on an internal bug tracker so not
shareable.

**Comment by gramster** [comment]
I just checked and it looks like their response is WAI. They say:

"The majorTicks option is the labels for major ticks, which should be an array of strings.  You have just a single number.
The minorTicks option is the *number* of minor ticks to draw, typically a small number, whereas you specified 100000."

**Comment by VelizarVESSELINOV** [comment]
Outside the crash, there are some API quality challenges:
minorTicks and majorTicks have very similar name but it is used for different purposes one is number the other is a string array. As you can see in highchart people are using different property names for different purposes like minorTickColor, minorTickLength, minorTick, minorTickInterval, etc.

In most of chart package, tick is expressed as a value and not as a number of subdivisions.

**Comment by gramster** [comment]
I doubt Charts are going to change their API. API changes are expensive and break existing dependencies.

**Comment by VelizarVESSELINOV** [comment]
I understand your doubt for Chart, my worry is that with this conservatism and very limited initial design, I'm moving away from Chart and starting to use more other packages like Bokeh that don't have so big legacy "freeze" problem.

**Comment by gramster** [comment]
Moved to https://github.com/googledatalab/datalab/issues/19
