### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/datalab#732]
When execute a query appear the error, same query on bigquery console work propertly.

Thanks

UnicodeEncodeError                        Traceback (most recent call last)
/usr/local/lib/python2.7/dist-packages/IPython/core/formatters.pyc in __call__(self, obj)
    335                 pass
    336             else:
--> 337                 return printer(obj)
    338             # Finally look for special method names
    339             method = _safe_get_formatter_method(obj, self.print_method)

/usr/local/lib/python2.7/dist-packages/gcp/datalab/_bigquery.pyc in _repr_html_query_results_table(results)
    843 
    844 def _repr_html_query_results_table(results):
--> 845   return _table_viewer(results)
    846 
    847 

/usr/local/lib/python2.7/dist-packages/gcp/datalab/_bigquery.pyc in _table_viewer(table, rows_per_page, fields)
    834                                total_rows=total_count,
    835                                rows_per_page=rows_per_page,
--> 836                                data=json.dumps(data, cls=gcp._util.JSONEncoder))
    837 
    838 

UnicodeEncodeError: 'ascii' codec can't encode character u'\xd1' in position 1292: ordinal not in range(128)

QueryResultsTable job_oI70ggi6Nb8JDiwVJFL_Ac08SIw

**Comment by albertog** [comment]
how can I upgrade my datalab version on gce. There are anyware diferent to delete and re-create
thxs

**Comment by gramster** [comment]
Fixed in 74e417b6e85e5457ff74f1b106dde527489a5dfa

**Comment by Khalid-Monex** [comment]
Similar error 

---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
/usr/local/lib/python2.7/dist-packages/IPython/core/formatters.pyc in __call__(self, obj)
    335                 pass
    336             else:
--> 337                 return printer(obj)
    338             # Finally look for special method names
    339             method = _safe_get_formatter_method(obj, self.print_method)

/usr/local/lib/python2.7/dist-packages/gcp/datalab/_bigquery.pyc in _repr_html_query_results_table(results)
    843 
    844 def _repr_html_query_results_table(results):
--> 845   return _table_viewer(results)
    846 
    847 

/usr/local/lib/python2.7/dist-packages/gcp/datalab/_bigquery.pyc in _table_viewer(table, rows_per_page, fields)
    834                                total_rows=total_count,
    835                                rows_per_page=rows_per_page,
--> 836                                data=json.dumps(data, cls=gcp._util.JSONEncoder))
    837 
    838 

UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 2245: ordinal not in range(128)

**Comment by qimingj** [comment]
This was fixed and tested in https://github.com/GoogleCloudPlatform/datalab/commit/4fbd389de42c667b34e3b9ba30b67a7853351387. It has not been released yet through Datalab deployer though.
