### ISSUE TITLE
Update datalab version

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/datalab#744]
How can I update the version deployed on appengine when release a new version.

**Comment by VelizarVESSELINOV** [comment]
:+1:

**Comment by gramster** [comment]
You would need to do a new deployment. The deployer by default picks up the latest release for managed VMs.

**Comment by VelizarVESSELINOV** [comment]
How I know that there is a new version?
I have version: 0.5.20160303, how do I know if it I need to redeploy DataLab?
How do I know what it is latest version available to deploy? And what it is available in the latest version?

On GitHub there is only one flagged release: v0.5.20151012-beta

**Comment by gramster** [comment]
There is a notification banner that shows up if there is a new version

**Comment by VelizarVESSELINOV** [comment]
Never saw the banner, probably not using enough Datalab to see it. It is good to know that I'm using the latest version.

**Comment by parthea** [comment]
If 0.5.20160303 is a published version, it would be great to see the release details here:
https://github.com/GoogleCloudPlatform/datalab/wiki/Release-Info
