### ISSUE TITLE
DataLab is not avialable in Europe

### ISSUE THREAD

**Issue by abdhk383** [GoogleCloudPlatform/datalab#749]
Hi,

I tried to employ dataLab capabilities in my daily data analysis in my office in Europe. Unfortunately, I get the message that this feature is only available in USA. Is there a possibility to get it also for Europe soon?

**Comment by gramster** [comment]
Yes. You will be able to run locally or in GCE.  See https://github.com/googlecloudplatform/datalab/wiki/Getting-Started
