### ISSUE TITLE
%chart: Move from Google Charts to plotly.js

### ISSUE THREAD

**Issue by gramster** [GoogleCloudPlatform/datalab#759]
We may need a hybrid of the two so we can fill in missing charts. E.g. plotly.js has heatmaps (2D histo) but does not have Sankey diagrams.

**Comment by VelizarVESSELINOV** [comment]
: +1: if you can add the support on several chart packages more advanced from the basic Google Charts it will be great. If you can also add Bokeh by default it will be great.

If you can go further and add solutions like Bokeh server to create more interactive plots and server rendered plots it will be just perfect.

**Comment by gramster** [comment]
Moved to https://github.com/googledatalab/datalab/issues/15
