### ISSUE TITLE
Project is null in local datalab setup

### ISSUE THREAD

**Issue by parthea** [GoogleCloudPlatform/datalab#763]
Hello,

I'm running datalab in a local development environment . I'm unable to run any queries using gcp.bigquery. I ran `gcloud init` and it appears that the project id is correct in the output of `gcloud init` , however I receive the following exception in the local datalabs web interface.

```
/usr/local/lib/python2.7/dist-packages/gcp/bigquery/_query.pyc in to_dataframe(self, start_row, max_rows, use_cache)
    280       A Pandas dataframe containing the table data.
    281     """
--> 282     return self.results(use_cache=use_cache) \
    283         .to_dataframe(start_row=start_row, max_rows=max_rows)
    284 

/usr/local/lib/python2.7/dist-packages/gcp/bigquery/_query.pyc in results(self, use_cache)
    213     """
    214     if not use_cache or (self._results is None):
--> 215       self.execute(use_cache=use_cache)
    216     return self._results.results
    217 

/usr/local/lib/python2.7/dist-packages/gcp/bigquery/_query.pyc in execute(self, table_name, table_mode, use_cache, priority, allow_large_results)
    426     """
    427     job = self.execute_async(table_name=table_name, table_mode=table_mode, use_cache=use_cache,
--> 428                              priority=priority, allow_large_results=allow_large_results)
    429     self._results = job.wait()
    430     return self._results

/usr/local/lib/python2.7/dist-packages/gcp/bigquery/_query.pyc in execute_async(self, table_name, table_mode, use_cache, priority, allow_large_results)
    390                                                  table_definitions=self._external_tables)
    391     except Exception as e:
--> 392       raise e
    393     if 'jobReference' not in query_result:
    394       raise Exception('Unexpected response from server')

RequestException: Not found: Project null
```

**Comment by gramster** [comment]
How are you running it, and on what platform? The container/datalab/run.sh script which runs locally maps your ~/.config directory to a directory in the container so Datalab can get hold of your access token, project ID etc. Its possible that isn't right for your setup.

**Comment by parthea** [comment]
I am running the container/datalab/run.sh script on linux . 

I added the 'shell'  argument to enter into the container. I can see my project number after entering the following command.
`echo $DATALAB_PROJECT_NUM`

I followed these instructions to [initialize](https://github.com/GoogleCloudPlatform/datalab/wiki/Development-Environment) and [build/run](https://github.com/GoogleCloudPlatform/datalab/wiki/Build-and-Run) datalabs. 

I will run through the commands from the beginning to make sure I didn't miss anything. Is there anything else I can check for in the container?

> The container/datalab/run.sh script which runs locally maps your ~/.config directory to a directory in the container so Datalab can get hold of your access token, project ID etc. Its possible that isn't right for your setup.

I have datalabs running locally, which is great. I want to use the project that I have configured (see output of `gcloud config list`. Can you help me identify which is the right configuration for my setup?

```
tony@tonypc:~/.config/gcloud$ gcloud config list
Your active configuration is: [default]

[compute]
region = us-central1
zone = us-central1-f
[core]
account = tonypartheniou@xxxxx.com
disable_usage_reporting = True
project = xx-xxx-xxx
```

**Comment by gramster** [comment]
In datalab, what do you see if you enter this in a cell:

    import gcp
    gcp.Context.default().project_id

**Comment by parthea** [comment]
Output from datalabs cell
```
import gcp
gcp.Context.default().project_id

'null'
```

Output from container
```
root@fbcd9692fed6:/# echo $DATALAB_PROJECT_NUM
XXXXXXXXXXXX

```

**Comment by parthea** [comment]
Thanks for your help. The issue is solved after running the following command in the container

'gcloud config set project myProject'

**Comment by gramster** [comment]
That does suggest that your .config was not getting mapped in correctly. Its also possible that on your desktop you have a very new version of gcloud and it is no longer writing to the location we are using  (but the version in the container is older so still works).

**Comment by parthea** [comment]
> That does suggest that your .config was not getting mapped in correctly. Its also possible that on your desktop you have a very new version of gcloud and it is no longer writing to the location we are using (but the version in the container is older so still works).

I'm re-opening this issue. I think the latter may be the case. 

I encountered the following warning message during gcloud setup

```
tony@TonyLinuxDesktop:~/tools$ gcloud config set project myProject
Loading legacy configuration file: [/home/tony/.config/gcloud/properties]
This configuration file is deprecated and will not be read in a future
gcloud release.  gcloud will automatically migrate your current settings to the
new configuration format the next time you set a property by running:
  $ gcloud config set PROPERTY VALUE
You may also run:
  $ gcloud init
to create a new configuration and walk you through initializing some basic
settings.  You can find more information on named configurations by running:
  $ gcloud topic configurations

WARNING: Creating and activating new configuration [default].
WARNING: Importing legacy user properties.

```

I also found a related post on [stackoverflow](http://stackoverflow.com/questions/34813383/updating-from-user-based-configuration-file)

**Comment by gramster** [comment]
Closing this as it is obsolete now. You either have to call set_project_id() in the notebook or set the PROJECT_ID environment variable in the Docker machine.
