### ISSUE TITLE
DataFrame 2 BigQuery challenges

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/datalab#770]
I tried several ways to move data from DataFrame (DF) to BigQuery (BQ).

Please find my results:

1. DF2CSV2BQ
DF2CSV: 13 seconds
CSV2BQ: 40 seconds (63 **seconds** between creation and last modification)
Output:
<img width="325" alt="tabledf2csv2bq" src="https://cloud.githubusercontent.com/assets/8209940/12987861/dcd5556a-d0b2-11e5-98f4-42026d809e16.png">

2. DF2BQ
DF2BQ: 450 seconds  (65 **minutes** between creation and last modification)
After the `insert_data()` the Table was empty (0 MB), after a few minutes/hour the data will appear in the table.
Output:
<img width="338" alt="tabledf2bq" src="https://cloud.githubusercontent.com/assets/8209940/12987867/e695ffbe-d0b2-11e5-88f5-ef95af55b299.png">

The results are not the same:
 1. DF2BQ is slow, even when the Python operation is finished the data are fully available only **1 hour after**.
 2. in DF2CSV2BQ the missing values are `null`, in the DF2BQ the missing values are `NaN`
 3. The final table sizes are not the same (CSV: 121 MB, DF2CSV2BQ: **83 MB**, DF2BQ: **194 MB** the cost of storage of `NaN`?)
 4. The rows order is lost with DF2BQ

As concrete issues:
 1. Consistency between `null` or `NaN`, `null` looks more appropriated.
 2. Improve the performance of DF2BQ
 3. DB2BQ keep the order of the rows

Maybe will be an easy fix is to replace `insert_data()` function with ~3 lines of code:

1. create a CSV file in memory
2. save it as temporary bucket
3. load the temporary file in BigQuery

**Comment by gramster** [comment]
Moved to https://github.com/googledatalab/datalab/issues/12
