### ISSUE TITLE
Update sikit-learn to version 0.17

### ISSUE THREAD

**Issue by oelshocht** [GoogleCloudPlatform/datalab#771]
Datalab includes version 0.16.1 although version 0.17 (November 2015) is available.

There are API changes between these 2 versions (http://scikit-learn.org/stable/whats_new.html) that make it cumbersome to share code.

Would you update scikit-learn to the latest version?

**Comment by VelizarVESSELINOV** [comment]
:+1:

**Comment by gramster** [comment]
The next release will have most packages updated.

**Comment by gramster** [comment]
Fixed in 6bbe1fde
