### ISSUE TITLE
Use AVRO format when exporting from BigQuery to Dataframe

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/datalab#787]
Code example:

```python
    n1 = time()
    file = "{}/{}.msg".format(dataset, table)
    buffer = BytesIO(data_bucket.item(file).read_from())
    df = read_msgpack(buffer)
    n2 = time()

    print("1a. MessagePack to Dataframe: {}".format(n2 - n1))

    n1 = time()
    q = 'SELECT * FROM [{}.{}]'.format(dataset, table)
    r = Query(q).results()
    df = r.to_dataframe()
    n2 = time()

    print("1b. BigQuery to Dataframe: {}".format(n2 - n1))
```

Results:
```
1a. MessagePack to Dataframe: 2.28054285049
1b. BigQuery to Dataframe: 493.655420065
```
I can accept that BigQuery is slower than reading from MessagePack from storage.Bucket, but 216 times slower is maybe too much? If I understand correctly 46 seconds is the query time and 8 minutes is the cost of transfer of 84 MiB binary data probably using an intermediate verbose JSON format not adapted for "big data".

BigQuery
![image](https://cloud.githubusercontent.com/assets/8209940/13862358/0458007a-ec50-11e5-8106-db52b29c2dcb.png)

When the results are cached the results can be relatively fast, MessagePack equivalent.

```
Bytes Processed	0 B (results cached)
Query complete (2.2s elapsed, cached)
```
132 columns (1 TIMESTAMP and 131 FLOAT)
![image](https://cloud.githubusercontent.com/assets/8209940/13862394/3ed895de-ec50-11e5-942d-c12813a6843b.png)

**Comment by VelizarVESSELINOV** [comment]
Any plans to:
-  access to faster dataframe storage solution at GCP? (BigTable maybe?)
-  replace the inefficient JSON with something more adapted for big data like Avro for the exchange between Pandas Dataframe and BigQuery [announced 2 weeks ago](https://cloud.google.com/blog/big-data/2016/03/improve-bigquery-ingestion-times-10x-by-using-avro-source-format)?

**Comment by gramster** [comment]
Using AVRO is a good idea. Probably worth looking at https://github.com/tebeka/fastavro too.

**Comment by gramster** [comment]
Moved to https://github.com/googledatalab/datalab/issues/11
