### ISSUE TITLE
Access denied errors when reading from GCS give unhelpful exception

### ISSUE THREAD

**Issue by jtigani** [GoogleCloudPlatform/datalab#797]
When I try to open gs://tigani/train.txt, I get a HTTP Request failed error, without any other information.
This was an access issue, and when I fixed access control, the problem went away. But this is an unhelpful error to get.

<ipython-input-12-862ce46ddf51> in <module>()
      1 import gcp
----> 2 gcp.storage.Bucket('tigani').item('train.txt').read_from()

/usr/local/lib/python2.7/dist-packages/gcp/storage/_item.pyc in read_from(self)
    169       return self._api.object_download(self._bucket, self._key)
    170     except Exception as e:
--> 171       raise e
    172 
    173   def write_to(self, content, content_type):

RequestException: HTTP request failed

**Comment by gramster** [comment]
Fixed in 630b1ec42558be132c88ea825d63f0cc490552a9
