### ISSUE TITLE
No refresh button/Can't commit

### ISSUE THREAD

**Issue by allensussman** [GoogleCloudPlatform/datalab#810]
If I go to datalab and click on "git repository", I can see new commits to the datalab_main branch in  "Recent Commits" on the right, but the changes from those commits don't show up in the "Source Code" and I have no option to Refresh.  I can't commit anything while I'm having this issue, I get the error "Create commit failed.  A new commit cannot be created because your changes are currently behind the HEAD of alias.  Please perform a refresh before committing your changes."  My coworkers who are working on this branch and repo are not having these problems.

**Comment by qimingj** [comment]
Allen, the team that developed source repository UI is investigating this. I'll keep you posted.

**Comment by qimingj** [comment]
Issue was resolved after Allen's workspace was reset.
