### ISSUE TITLE
Quandl package request

### ISSUE THREAD

**Issue by kkimdev** [GoogleCloudPlatform/datalab#824]
Quandl python API package https://github.com/quandl/quandl-python

**Comment by gramster** [comment]
Seems highly unlikely we would bundle this; just do:

    %bash
    pip install quandl-python

in a code cell at the start of any notebook that needs it.

**Comment by kkimdev** [comment]
Yeah I was already doing that so it wasn't a practical issue.  Though, is there an established criterion for a package inclusion?  I can't speak for everyone, but I would image that quandl is a reasonably popular package.  Their dataset was even used in the Google Datalab official tutorial https://cloud.google.com/solutions/machine-learning-with-financial-time-series-data (but pre-cached behind Big Query)

**Comment by nikhilk** [comment]
At some point, I'd like to have a regular survey to see top-packages suggested, and evaluate incorporating the ones that rise to the top.

Ideally we'd want to factor in things like popularity, how generally applicable it is, as well as things like size.

There are some thoughts on making it simple for automating addition on extra packages, as well as providing guidance around creating derived containers that should help when there are specific needs that don't generalize.

**Comment by kkimdev** [comment]
Sounds good 👍

**Comment by gramster** [comment]
This should be addressed by https://github.com/GoogleCloudPlatform/datalab/issues/854
