### ISSUE TITLE
Feature: enable custom library additions 

### ISSUE THREAD

**Issue by Di-Ku** [GoogleCloudPlatform/datalab#826]
This is a frequent ask: 
"How can I add a set of Python (or other) packages?"
Our current answer is to add a cell to a notebook and do pip install or whatever else you do with a shell command. That is a good workaround but doesn't really provide a good story across notebooks and restarts.

(Capturing discussion with Graham and Bradley)
A better way would be for us to execute a set of commands upon startup from some file external to the container. Interestingly, down the road, the same startup script could apply to someone running a remote kernel in GCE  (i.e. split between kernel & web-server)

**Comment by gramster** [comment]
Also from discussion: use an optional environment variable that can be set
to point to a GCS bucket or file under /content and will run that as part
of startup.

**Comment by parthea** [comment]
I would be interested to work on this feature request if it is not already assigned to another team member.

**Comment by gramster** [comment]
Sure, if you want to give it a go. Some pointers:

- should handle a local file path or a GCS object URL
- you probably want to do it from containers/datalab/content/run.sh

We're about to change auth in the container to be optional (with a sign in
button in tree view, for if there are no cached credentials). So if the
file is in GCS, we should be robust in the face of auth failure.

**Comment by nikhilk** [comment]
I'd propose that we prioritize just a local file (specifically a file in the datalab directory).

This file can exist in GCE as well (by virtue of the user placing it explicitly in the right path on the VM, just like they would for local scenarios) rather than having a local and GCS story in parallel.

**Comment by nikhilk** [comment]
Additionally to the extent this looks like something we didn't invent that would be good... start with something like a requirements.txt file that can be used to do pip install on startup.

Separately we should document how to build derived docker containers, as repeated installs on each instantiation of the container gets frustrating after a few times.

**Comment by gramster** [comment]
Sounds good; that makes it a lot simpler. We don't need an environment
variable then unless we want to use that as a way of supporting multiple
configs.

**Comment by gramster** [comment]
Related to the building of derived containers, we could have the build
script do something similar - see if a file with some name is present and
if it is concatenate it to the base Dockerfile before building the
container.

**Comment by gramster** [comment]
Done in b78afa7
