### ISSUE TITLE
Developer Console link is going to APIs library

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/datalab#839]
We would expect that Developer Console link will go to GCP Dev Console and not to the APIs library page:
![image](https://cloud.githubusercontent.com/assets/8209940/15266206/f7341b98-1951-11e6-868b-6fb5ddf630aa.png)

Is it normal?

**Comment by gramster** [comment]
That link doesn't exist anymore in master. Closing as obsolete.
