### ISSUE TITLE
Run a script (/content/datalab/startup.sh) upon startup if it exists

### ISSUE THREAD

**Issue by gramster** [GoogleCloudPlatform/datalab#854]
The /content/ directory is used to map in the external volume of the user. With this change users can easily add some custom code to run at startup; e.g. to install/upgrade packages.

Note: this applies to local run or GCE hosted only; not managed VMs.

**Comment by gramster** [comment]
One question this begs: should we support an arbitrary script or just a list of packages that will be pip-installed? The latter is more secure but also more limited.

**Comment by Di-Ku** [comment]
I would suggest going with an arbitrary script. User is expected to have full control over the machine/VM and the directory mounted in it. Specifically, the execution is sandboxed to a container.
On the flip side, what if I want to install using conda? Or check version before installing? The interface seems a lot cleaner with a shell script - and it is similar to the per-notebook guidance of %%bash cell. 

But you have a good point about the security implications - so this should probably be listed in Bradley's doc.

**Comment by gramster** [comment]
Fixed in 3eb7273
