### ISSUE TITLE
502 Bad Gateway after Datalab deployment

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/datalab#863]
After redeployment of Datalab on a specific Google project, all the Datalab pages have 502 Bad Gateway error message. Any idea how to fix this?

**Comment by ojarjur** [comment]
Sorry that this hit you; we had an issue with deployments last night that has been fixed.

Please try redeploying and let us know if things work again.

**Comment by VelizarVESSELINOV** [comment]
It is working now, thanks.

Very good reactivity on GitHub :)
