### ISSUE TITLE
The `nextJupyterPort` variable should always be initialized to a free port

### ISSUE THREAD

**Issue by ojarjur** [GoogleCloudPlatform/datalab#891]
Currently, at startup of the NodeJS server, the `nextJupyterPort` variable is initialized to 9000. When we try to launch a Jupyter server, we will verify that port is free and retry (with the next port) if it isn't, but that will count against the retry count for that creation attempt.

It would be better if the logic to get the next Jupyter port just always returned a port that was (at that time) unused.

**Comment by VelizarVESSELINOV** [comment]
Thanks :)
